name: CI/CD
on: pull_request
jobs:
  build:
    name: Build and test PR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}
    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 beregost
    - name: Deploy (dry run)
      run: |
        kubectl version
        kubectl apply --dry-run=server -k kustomize/clusters/do-sfo2-beregost
