name: Pull Request
on: pull_request
jobs:
  build:
    name: Build and test PR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up kubectl
      uses: matootie/dokube@v1.3.4
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        clusterName: beregost
        version: "1.19.7"
    - name: Deploy (dry run)
      run: |
        kubectl apply --dry-run=server -k kustomize/clusters/do-sfo2-beregost
